### ISSUE TITLE
Allow for first-class steps

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/vertx-engine#39]
Like Ansible has `yum`, allow for steps to be keys with arguments in our DSL.  This will probably require an annotation, and remove the need for specifying the fully-qualified class name in the DSL.

**Comment by LightGuard** [comment]
I understand what you're getting at, but could you give a use case example or something we could write a test for?

**Comment by ke4roh** [comment]
```
- name: Make a thing
  copy: &rememberThis 
     from: "{{ data | long | filter | string }}"
     data: "{{doc.here}}"
     register: aPlace
- name: Copy the other thing
  copy: 
     <<: *rememberThis
     from: "{{doc.q}}"
     register: newPlace
```
