### ISSUE TITLE
DSL cleanup

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/vertx-engine#65]
* Get rid of the vars section - just fold it directly under the step short name.
* Make the step config accessible inside the environment so that variable interpretation can do its thing

```
name: Lorem ipsum
concat: 
   from: "{{doc.ca}}"
   append: "o"
register: "dolor"
when: {{doc.c > 5}}
```
